services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ml:
    build:
      context: ./ml
    container_name: ml-service
    ports:
      - "3000:3000"
    restart: unless-stopped

  app:
    build:
      context: ./app
    container_name: app-service
    depends_on:
      - ml
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
      MANIPULATION_DETECTOR_BASE_URL: http://ml:3000
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017
    restart: unless-stopped

volumes:
  mongodb_data:
